from datetime import UTC, datetime, timedelta
from email import policy
from email.message import EmailMessage
from email.parser import BytesParser
import json

import pytest

from contract_ipo_monitor.gmail_delivery import DefinitiveDeliveryFailure, MIME_TREE_VERSION, UnknownDelivery, message_content_sha256
from contract_ipo_monitor.notifications import EmailOutbox, report_message

NOW = datetime(2026, 10, 5, 22, tzinfo=UTC)
ADDRESS = "recipient@example.com"


def make_message(event="event-one", *, test=False):
    report = {"completed_at": NOW.isoformat(), "status": "degraded", "health": {}, "counts": {},
              "trade_ideas": [{"symbol": "EXAMPLE", "exchange": "NASDAQ", "currency": "USD", "action": "conditional_buy",
                               "entry": 101.0, "invalidation": 95.0, "target": 113.0, "price_as_of": "2026-10-02",
                               "reasons": ["Comparable reported growth"], "risks": ["No predictive probability"],
                               "evidence_urls": ["https://www.sec.gov/example"]}]}
    return report_message(report, sender=ADDRESS, recipient=ADDRESS, event_key=event, created_at=NOW, test=test)


def enqueue(outbox, raw=None, event="event-one", *, expiry=None):
    return outbox.enqueue(event, raw or make_message(event), ADDRESS, now=NOW, expires_at=expiry or NOW + timedelta(hours=6))


def proof(row):
    return {"gmail_message_id": "provider-one", "thread_id": "thread-one", "verified_at": NOW.isoformat(),
            "provider_accepted_at": NOW.isoformat(), "recipient": ADDRESS, "sender": ADDRESS,
            "delivered_label": "INBOX", "raw_content_sha256": row["raw_sha256"], "readback_raw_sha256": row["raw_sha256"],
            "rfc822_id": row["rfc822_id"], "content_sha256": message_content_sha256(bytes(row["raw_message"])),
            "content_sha256_version": MIME_TREE_VERSION}


def historical_message():
    message = EmailMessage(policy=policy.SMTP)
    message["From"], message["To"] = ADDRESS, ADDRESS
    message["Subject"] = "Historical IPO research"
    message["Message-ID"] = "<historical-report@ipo-monitor.local>"
    message.set_content("Historical report. No holding assumed.\n")
    message.add_attachment(b"# Historical report\n", maintype="text", subtype="markdown", filename="research-report.md")
    message.add_attachment(b'{"holdings":[],"trade_ideas":[]}', maintype="application", subtype="json", filename="research-report.json")
    return message.as_bytes()


@pytest.mark.parametrize("explicit_version", [False, True])
def test_historical_plaintext_markdown_json_receipt_preserves_legacy_digest_and_saved_bytes(tmp_path, explicit_version):
    outbox = EmailOutbox(tmp_path / "historical-mail.db")
    raw = historical_message()
    identifier = enqueue(outbox, raw)
    row = outbox.lease(NOW)
    legacy = proof(row)
    legacy["content_sha256"] = message_content_sha256(raw, version="leaf-v1")
    # This value was captured from the old implementation before MIME-tree
    # hashing was introduced; it is not generated by this test's new default.
    assert legacy["content_sha256"] == "2df12321c170ab9775f49cc3c0f3318bc7f847b704a1053b3d8b4b74b0a51ecd"
    if explicit_version:
        legacy["content_sha256_version"] = "leaf-v1"
    else:
        legacy.pop("content_sha256_version")
    outbox._settle(row, status="sent", now=NOW, receipt=legacy)
    before = outbox.get(identifier)
    assert EmailOutbox.historical_receipt_matches(before, json.loads(before["receipt_json"]))
    assert not EmailOutbox._receipt_matches(before, legacy)
    assert outbox.get(identifier) == before and before["raw_message"] == raw


@pytest.mark.parametrize("version", ["unknown", "", None, False, []])
def test_unknown_receipt_version_cannot_authorize_live_or_historical_delivery(tmp_path, version):
    outbox = EmailOutbox(tmp_path / "mail.db")
    identifier = enqueue(outbox)
    row = outbox.get(identifier)
    receipt = {**proof(row), "content_sha256_version": version}
    assert not EmailOutbox._receipt_matches(row, receipt)
    assert not EmailOutbox.historical_receipt_matches(row, receipt)
    assert outbox.get(identifier)["status"] == "pending"


def test_missing_version_does_not_reinterpret_new_digest_as_a_legacy_receipt(tmp_path):
    outbox = EmailOutbox(tmp_path / "mail.db")
    identifier = enqueue(outbox)
    row = outbox.get(identifier)
    receipt = proof(row)
    receipt.pop("content_sha256_version")
    assert not EmailOutbox._receipt_matches(row, receipt)
    assert not EmailOutbox.historical_receipt_matches(row, receipt)


def test_mail_keeps_exact_report_attachments_and_no_assumed_position():
    message = BytesParser(policy=policy.default).parsebytes(make_message(test=True))
    assert message["To"] == ADDRESS and "PIPELINE TEST" in message["Subject"]
    text = message.get_body(preferencelist=("plain",)).get_content()
    assert "Holdings on file: none" in text and "not execution instructions" in text
    assert "101.0" in text and "5 sessions" in text and "15" in text
    attachments = {part.get_filename(): part.get_payload(decode=True) for part in message.iter_attachments()}
    assert set(attachments) == {"research-report.pdf", "research-report.json"}
    assert attachments["research-report.pdf"].startswith(b"%PDF-")
    assert b'"entry": 101.0' in attachments["research-report.json"]


@pytest.mark.parametrize("open_at,close_at", [
    ("2026-10-06T08:30:00", "2026-10-06T15:00:00-05:00"),
    ("2026-10-06T08:30:00-05:00", "2026-10-06T15:00:00"),
    ("2026-10-06T15:00:00-05:00", "2026-10-06T08:30:00-05:00"),
    ("2026-10-06T08:30:00-05:00", "2026-10-06T08:30:00-05:00"),
])
def test_plaintext_report_does_not_invent_times_from_ambiguous_or_reversed_windows(open_at, close_at):
    report = {"completed_at": NOW.isoformat(), "trade_ideas": [{
        "symbol": "EXAMPLE", "action": "conditional_buy", "exchange": "NASDAQ", "currency": "USD",
        "entry": 101, "invalidation": 95, "target": 113,
        "strategy": {"timing": {"entry_window": {"local_timezone": "America/Chicago",
                                                "local_open": open_at, "local_close": close_at}}},
    }]}
    raw = report_message(report, sender=ADDRESS, recipient=ADDRESS, event_key="timing-test", created_at=NOW)
    message = BytesParser(policy=policy.default).parsebytes(raw)
    text = message.get_body(preferencelist=("plain",)).get_content()
    assert "calendar unavailable; verify exchange hours with your broker" in text
    assert "08:30 AM" not in text and "03:00 PM" not in text


def test_publication_is_idempotent_and_cannot_change_content_or_recipient(tmp_path):
    outbox = EmailOutbox(tmp_path / "mail.db")
    first = enqueue(outbox)
    assert enqueue(outbox) == first
    with pytest.raises(ValueError, match="conflicting"):
        enqueue(outbox, make_message("different"))
    assert outbox.states() == {"pending": 1}


def test_only_one_owner_leases_a_message_and_verified_delivery_is_bound(tmp_path):
    path = tmp_path / "mail.db"
    first, second = EmailOutbox(path), EmailOutbox(path)
    identifier = enqueue(first)
    row = first.lease(NOW)
    assert second.lease(NOW) is None
    first._settle(row, status="sent", now=NOW, receipt=proof(row))
    assert first.get(identifier)["status"] == "sent"
    with pytest.raises(RuntimeError, match="no longer owned"):
        second._settle(row, status="sent", now=NOW, receipt=proof(row))


def test_crash_after_claim_becomes_unknown_and_never_retries(tmp_path):
    path = tmp_path / "mail.db"
    first = EmailOutbox(path)
    identifier = enqueue(first)
    first.lease(NOW)
    restored = EmailOutbox(path)
    assert restored.lease(NOW + timedelta(minutes=6)) is None
    assert restored.get(identifier)["status"] == "unknown"


def test_uncertain_post_preserves_partial_receipt_and_no_resend(tmp_path):
    outbox = EmailOutbox(tmp_path / "mail.db")
    identifier = enqueue(outbox)
    calls = []

    class Transport:
        def deliver(self, *args):
            calls.append(args)
            raise UnknownDelivery("timeout", partial_receipt={"gmail_message_id": "accepted-but-unread"})

        def reconcile(self, *args):
            return None

    transport = Transport()
    assert outbox.deliver_once(transport, now=NOW)["status"] == "unknown"
    assert "accepted-but-unread" in outbox.get(identifier)["receipt_json"]
    assert outbox.deliver_once(transport, now=NOW + timedelta(hours=1)) is None
    assert outbox.reconcile_unknown(transport, now=NOW + timedelta(hours=1)) == []
    assert len(calls) == 1


def test_unknown_recovery_requires_exact_recipient_content_and_identity(tmp_path):
    outbox = EmailOutbox(tmp_path / "mail.db")
    identifier = enqueue(outbox)
    row = outbox.lease(NOW)
    outbox._settle(row, status="unknown", now=NOW)

    class Transport:
        result = {**proof(row), "recipient": "another@example.com"}

        def reconcile(self, *args):
            return self.result

    transport = Transport()
    assert outbox.reconcile_unknown(transport, now=NOW) == []
    assert outbox.get(identifier)["status"] == "unknown"
    transport.result = proof(row)
    assert outbox.reconcile_unknown(transport, now=NOW) == [{"id": identifier, "status": "sent", "reconciled": True}]
    assert outbox.get(identifier)["status"] == "sent"


def test_known_preflight_failure_can_retry_but_expired_research_cannot_send(tmp_path):
    outbox = EmailOutbox(tmp_path / "mail.db")
    identifier = enqueue(outbox)

    class Transport:
        def deliver(self, *args):
            raise DefinitiveDeliveryFailure("preflight_unavailable", safe_to_retry=True)

    assert outbox.deliver_once(Transport(), now=NOW)["status"] == "pending"
    assert outbox.get(identifier)["attempts"] == 1
    assert outbox.deliver_once(Transport(), now=NOW + timedelta(hours=7)) is None
    assert outbox.get(identifier)["status"] == "expired"


def test_unverified_acceptance_is_not_sent(tmp_path):
    outbox = EmailOutbox(tmp_path / "mail.db")
    identifier = enqueue(outbox)

    class Transport:
        def deliver(self, *args):
            return {"gmail_message_id": "accepted"}

    assert outbox.deliver_once(Transport(), now=NOW)["status"] == "unknown"
    assert outbox.get(identifier)["sent_at"] is None


def test_header_injection_is_rejected():
    with pytest.raises(ValueError):
        report_message({"completed_at": NOW.isoformat(), "status": "ok"}, sender=ADDRESS,
                       recipient=ADDRESS + "\nBcc: other@example.com", event_key="bad", created_at=NOW)


def test_unknown_reconciliation_uses_only_the_persisted_own_post_acknowledgement(tmp_path):
    outbox = EmailOutbox(tmp_path / "mail.db")
    identifier = enqueue(outbox)
    row = outbox.lease(NOW)
    outbox._settle(row, status="unknown", now=NOW, receipt={"gmail_message_id": "own-post-id"})
    class Transport:
        def reconcile(self, identity, recipient, raw, *, provider_message_id):
            assert provider_message_id == "own-post-id"
            assert identity == row["rfc822_id"] and raw == bytes(row["raw_message"])
            return {**proof(row), "gmail_message_id": provider_message_id,
                    "provider_rfc822_id": "<rewritten@mail.gmail.com>"}
    assert outbox.reconcile_unknown(Transport(), now=NOW) == [{"id": identifier, "status": "sent", "reconciled": True}]


@pytest.mark.parametrize("change", [{"verified_at": "yesterday"}, {"verified_at": "2026-10-05T22:00:00"},
                                   {"sender": "different@example.org"}, {"delivered_label": "DRAFT"},
                                   {"raw_content_sha256": "0"*64}, {"readback_raw_sha256": "unverified"}])
def test_partial_or_contradictory_provider_receipt_never_marks_sent(tmp_path, change):
    outbox = EmailOutbox(tmp_path / "mail.db")
    identifier = enqueue(outbox)
    class Transport:
        def deliver(self, *args):
            return {**proof(outbox.get(identifier)), **change}
    assert outbox.deliver_once(Transport(), now=NOW)["status"] == "unknown"
    assert outbox.get(identifier)["sent_at"] is None
